### ISSUE TITLE
Feature Request: Nifty.org HTML chapters.

### ISSUE THREAD

**Issue by jtoronto** [DreamCobbler/fiction-dl#14]
Seems F-DL only works on plain-text chapters, but unfortunately some authors use HTML pages for each chapter and the extractor doesn't seem to work with those, generating the error:
```
ERROR:root:Failed to read metadata from the first chapter of the story.
ERROR:root:Failed to scan the story.
```

**Comment by DreamCobbler** [comment]
Since HTML-formatted stories don't use any consistent format for metadata, implementing this is currently impossible.

(f-dl needs to know where to look for metadata it requires, and lack of a constant layout of a page makes the problem of reading the information unsolvable. Text stories have their metadata in the first three lines - most of the text stories, anyway - so they can be read, but the structure of the page of HTML stories is dependent on the author's whim and nothing else.)
