### ISSUE TITLE
[Improvement] Use AO3 official downloads.

### ISSUE THREAD

**Issue by laundmo** [DreamCobbler/fiction-dl#4]
AO3 offers downloads in multiple formats, namely: AZW3, EPUB, MOBI, PDF, HTML
Direct links to these are very easy to get: `https://archiveofourown.org/downloads/<story_id>/a.<extension>` (the `a` here can be any text, by default it is the stories name, but it does not matter)

This has the potential to simplify the downloading and reduce load on ao3 and potential 429 - Too Many Requests errors.

**Comment by DreamCobbler** [comment]
Thank you for the suggestion! I've implemented a variant of that in the newly released 1.6.0 - though instead of using the files provided by AO3 itself, fiction-dl now uses the single-page view of the story. Does the same thing, i.e. there's just one page-download per story, which both reduces the load on AO3 and vastly speeds up the download itself.
